### ISSUE TITLE
How can I find your contacts?

### ISSUE THREAD

**Issue by CheshireCaat** [maritaria/SideKik#3]
Good afternoon, I need to contact you for information on Sidekick
Ideally, you need to modify the library or any information to create a similar
I can donate a certain amount

**Comment by maritaria** [comment]
What do you need?

**Comment by CheshireCaat** [comment]
I would like to see an update for the library
More methods, such as CAPTCHA solution, search for groups and entry based on search results

Unfortunately, my knowledge is not enough at this point in time even to intercept the messenger's traffic

I was able to install it into my project, but I would like to understand how to modify / create methods for working with Kick.
